version: '3.8'
services:
  front:
    build:
      context: ./
      target: production
    command: echo baltringue
    ports:
      - "3300:3000"
    networks:
      - dockerlan
    restart: always

networks:
  dockerlan:
    driver: bridge
