version: '3.8'
services:
  front:
    image: gnos28/wildcode-front
    # volumes:
    #   - ./build:/front/build
    command: serve -s build
    ports:
      - "3300:3000"
    # networks:
    #   - dockerlan
    restart: always

# networks:
#   dockerlan:
#     driver: bridge
